# Generated by Django 4.1.5 on 2023-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sub Menu',
                'verbose_name_plural': 'Sub Menu',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'verbose_name': 'Sub Menu', 'verbose_name_plural': 'Sub Menu'},
        ),
    ]
